---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      #name: https
      #protocol: HTTPS
      name: http-port-for-tls-origination
      protocol: HTTP
    hosts:
    - {{ .Values.nginx.host }}
    #tls:
    #  mode: MUTUAL
    #  serverCertificate: /etc/certs/cert-chain.pem
    #  privateKey: /etc/certs/key.pem
    #  caCertificates: /etc/certs/root-cert.pem
...