---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-nginx-mesh-external
  namespace: istio-system-egress
spec:
  host: {{ .Values.nginx.host }}
  # <TODO 1>
  # Why does the request from application pod fail if this destinationrule is exported to only the istio-system namespace?
  exportTo:
    - "."
  # <END TODO 1>
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS for connections to nginx
        # <TODO 2>
        # We want the destinationrule applied to just the istio-system namespace only so that we can trust our own ca-cert
        caCertificates: /etc/configmaps/ocp-ca-bundle/ca.crt
        #caCertificates: /etc/configmaps/trusted-ca-bundle/ca-bundle.crt
        # <END TODO 2>
        sni: {{ .Values.nginx.host }}
...