---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx
  namespace: mesh-external
spec:
  to:
    kind: Service
    name: nginx-ex
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
...