---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: {{ .Values.control_plane.namespace }}
spec:
  port:
    targetPort: http2
  tls:
    termination: edge
  to:
    kind: Service
    name: custom-ingressgateway
    weight: 100
  wildcardPolicy: None
...