---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: nginx-echo-headers
spec:
  selector:
    matchLabels:
      app: nginx-echo-headers
  mtls:
    mode: STRICT
...
    