---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mongo
spec:
  to:
    kind: Service
    name: mongo-ingressgateway
    weight: 100
  port:
    targetPort: mongo-tls
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
...
