---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  gateways:
  - {{ .Values.control_plane.namespace }}/default
  hosts:
  - {{ .Values.control_plane.ingressgateway.host }}
  http:
  - route:
    - destination:
        host: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port:
          number: 80
...