---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: oauth-proxy
spec:
  host: oauth-proxy
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
...
