---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: mtls-jwt-example
spec:
  targets:
  - name: productpage
  - name: nginx-echo-headers
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: {{ printf .Values.oidc_issuer_url | quote }}
      jwksUri: {{ printf "%v/v1/keys" .Values.oidc_issuer_url | quote }}
  principalBinding: USE_ORIGIN
...
