---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongodb
  namespace: {{ .Values.bookinfo_namespace }}
spec:
  hosts:
  - {{ .Values.mongodb.host }}
  addresses:
  - {{ .Values.mongodb.host }}
  ports:
  - number: {{ .Values.mongodb.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: {{ .Values.mongodb.host }}
...