---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signer
spec:
  selfSigned: {}
...
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-rootca
spec:
  secretName: ingressgateway-rootca
  issuerRef:
    kind: ClusterIssuer
    name: self-signer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
...
---  
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-rootca
spec:
  ca:
    secretName: ingressgateway-rootca
...
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-subca
spec:
  secretName: ingressgateway-subca
  issuerRef:
    kind: Issuer
    name: internal-rootca
  commonName: "ca.subca.cert-manager"
  isCA: true
...
---  
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-subca
spec:
  ca:
    secretName: ingressgateway-subca
...
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-subca2
spec:
  secretName: ingressgateway-subca2
  issuerRef:
    kind: Issuer
    name: internal-rootca
  commonName: "ca.subca2.cert-manager"
  isCA: true
...
---  
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-subca2
spec:
  ca:
    secretName: ingressgateway-subca2
...
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-cert
spec:
  # Secret names are always required.
  secretName: ingressgateway-cert
  commonName: {{ .Values.ingressgateway.cert.commonName }}
  dnsNames:
    - ingressgateway-cert
    - {{ .Values.ingressgateway.cert.commonName }}
  usages:
    - server auth
    - client auth  
  issuerRef:
    name: internal-subca
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
...
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-cert2
spec:
  # Secret names are always required.
  secretName: ingressgateway-cert2
  commonName: api-not-allowed-istio-system.apps-crc.testing
  dnsNames:
    - ingressgateway-cert2
    - api-not-allowed-istio-system.apps-crc.testing
  usages:
    - server auth
    - client auth  
  issuerRef:
    name: internal-subca2
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
...
