---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mongodb
  namespace: {{ .Values.control_plane.namespace }}
spec:
  selector:
    istio: mongo-ingressgateway
  servers:
  - hosts:
    - {{ .Values.mongodb.host }}
    port:
      name: mongo-tls
      number: 27018
      protocol: TLS
    tls:
      mode: ISTIO_MUTUAL # Compared to Mutual mode, this mode uses certificates, representing gateway workload identity, generated automatically by Istio for mTLS authentication.
...
