---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default
  namespace: {{ .Values.control_plane.namespace }}
spec:
  selector:
    app: custom-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ .Values.control_plane.ingressgateway.host }}
...