---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signer
spec:
  selfSigned: {}
...
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rootca
spec:
  secretName: rootca
  issuerRef:
    kind: ClusterIssuer
    name: self-signer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
...