---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: nginx-echo-headers
spec:
  selector:
    matchLabels:
      app: nginx-echo-headers
  rules:
  - from:
    # Require a valid jwt for all requests from the ingressgateway only
    - source:
        requestPrincipals:
          - "*"
        principals:
          - "cluster.local/ns/{{ .Values.control_plane.namespace }}/sa/istio-ingressgateway-service-account"
...
