---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default
  namespace: {{ .Values.control_plane.namespace }}
spec:
  selector:
    istio: {{ .Values.control_plane.ingressgateway.name }}
  servers:
  - port:
      number: 80
      name: http
      protocol: TLS
    hosts:
      - {{ .Values.control_plane.ingressgateway.host }}
    tls:
      mode: SIMPLE
      serverCertificate: /etc/secrets/custom-ingressgateway-cert/tls.crt
      privateKey: /etc/secrets/custom-ingressgateway-cert/tls.key
...