---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mongodb
  namespace: {{ .Values.control_plane.namespace }}
spec:
  selector:
    istio: mongo-ingressgateway
  servers:
  - hosts:
    - {{ .Values.mongodb.host }}
    port:
      name: tls
      number: 15443
      protocol: TLS
    tls:
      mode: MUTUAL
      credentialName: mongo-cert      
...
