---
# Source: service-mesh-operators/templates/subscriptions.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
spec:
  channel: "4.3"
  installPlanApproval: Manual
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Source: service-mesh-operators/templates/subscriptions.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
spec:
  channel: stable
  installPlanApproval: Manual
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Source: service-mesh-operators/templates/subscriptions.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
spec:
  channel: stable
  installPlanApproval: Manual
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Source: service-mesh-operators/templates/subscriptions.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
spec:
  channel: stable
  installPlanApproval: Manual
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
