apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
stringData:
  oauth2-proxy.cfg: |
    # Example: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example
    ## The OAuth Secret
    client_secret = {{ .Values.client_secret | quote }}
    ## Cookie Settings
    ## Secret   - the seed string for secure cookies; should be 16, 24, or 32 bytes
    ##            for use with an AES cipher when cookie_refresh or pass_access_token
    ##            is set
    cookie_secret = {{ .Values.cookie_secret | quote }}
