apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: okta
spec:
  hosts:
  - dev-338970.okta.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS