---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-nginx-mesh-external
  namespace: {{ .Values.egress.namespace }}
spec:
  host: istio-egressgateway.{{ .Values.egress.namespace }}.svc.cluster.local
  subsets:
  - name: nginx
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: {{ .Values.nginx.host }}
...