---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - {{ .Values.control_plane_namespace }}/default
  hosts:
  - {{ .Values.route_hostname }}
  http:
    - corsPolicy:
        allowCredentials: false
        allowHeaders:
          - X-Foo-Bar
        allowMethods:
          - GET
        allowOrigin:
          - example.com
        maxAge: 24h
      headers:
        response:
          add:
            name: test
      match:
      - uri:
          exact: /productpage
      - uri:
          exact: /login
      - uri:
          exact: /logout
      - uri:
          prefix: /api/v1/products
      route:
      - destination:
          host: productpage
          port:
            number: 9080
...