---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google
  namespace: {{ .Values.egress.namespace }}
spec:
  host: {{ .Values.google.host }}
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing {{ .Values.google.host }}
...