---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: {{ .Values.control_plane.egressgateway.namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: {{ .Values.control_plane.egressgateway.port }}
      name: mongo
      protocol: MONGO
    hosts:
    - {{ .Values.mongodb.host }}
...