---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: {{ .Values.control_plane.egressgateway.namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 27017
      name: tcp
      protocol: TCP
    hosts:
    - {{ .Values.mongodb.host }}
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
...