# kind: PeerAuthentication
# apiVersion: security.istio.io/v1beta1
# metadata:
#   name: nginx-echo-headers
# spec:
#   selector:
#     matchLabels:
#       app: nginx-echo-headers
#   mtls:
#     mode: DISABLE
