---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: service-mesh-patterns
spec:
  type: GitHub
  pathname: https://github.com/trevorbox/service-mesh-patterns.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: auth-service-mesh-operators
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - auth-service-mesh-operators
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: auth-service-mesh-operators
  labels:
    app: auth-service-mesh-operators
  annotations:
    apps.open-cluster-management.io/github-path: auth/helm/service-mesh-operators
    apps.open-cluster-management.io/github-branch: rhacm
spec:
  channel: {{ .Release.Namespace }}/service-mesh-patterns
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters

