---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-mongodb-mesh-external
  namespace: {{ .Values.control_plane.egressgateway.namespace }}
spec:
  host: istio-egressgateway.{{ .Values.control_plane.egressgateway.namespace }}.svc.cluster.local
  subsets:
  - name: mongodb
...