---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongodb
spec:
  hosts:
    - {{ .Values.mongodb.host }}
  ports:
    - name: mongo
      number: 27017
      protocol: MONGO
    - name: mongo-tls
      #number: 27018
      number: 443
      protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
...