---
kind: Secret
apiVersion: v1
metadata:
  name: istio-ca-secret
data:
  ca-cert.pem: {{ .Values.rootca.tls_crt }}
  ca-key.pem: {{ .Values.rootca.tls_key }}
  cert-chain.pem: ''
  key.pem: ''
  root-cert.pem: ''
type: istio.io/ca-root
...
