---
kind: Secret
apiVersion: v1
metadata:
  name: cacerts
data:
  ca-cert.pem: {{ .Values.rootca.tls_crt }}
  ca-key.pem: {{ .Values.rootca.tls_key }}
  cert-chain.pem: {{ .Values.rootca.tls_crt }}
  root-cert.pem: {{ .Values.rootca.ca_crt }}
type: istio.io/ca-root
...
