---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-mongo
spec:
  host: istio-egressgateway.{{ .Values.control_plane_namespace }}.svc.cluster.local
  subsets:
  - name: mongo
...