---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: {{ .Values.control_plane_namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: {{ .Values.egressgateway_port }}
      name: tcp
      protocol: TCP
    hosts:
    - {{ .Values.mongodb.host }}
...